# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.management_model_properties import ManagementModelProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementModelProperties(unittest.TestCase):
    """ManagementModelProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManagementModelProperties(self):
        """Test ManagementModelProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.management_model_properties.ManagementModelProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
