# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_speechtotext_v30_transcriptions_locales_get200_application_json_response import ApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse(unittest.TestCase):
    """ApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse(self):
        """Test ApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_speechtotext_v30_transcriptions_locales_get200_application_json_response.ApiSpeechtotextV30TranscriptionsLocalesGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
