# coding: utf-8

"""
    Speech to Text API v3.0

    Speech to Text API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_model_to_subscription(self):
        """Test case for copy_model_to_subscription

        Copy Model  # noqa: E501
        """
        pass

    def test_create_dataset(self):
        """Test case for create_dataset

        Create Dataset  # noqa: E501
        """
        pass

    def test_create_endpoint(self):
        """Test case for create_endpoint

        Create Endpoint  # noqa: E501
        """
        pass

    def test_create_evaluation(self):
        """Test case for create_evaluation

        Create Evaluation  # noqa: E501
        """
        pass

    def test_create_hook(self):
        """Test case for create_hook

        Create Web Hook  # noqa: E501
        """
        pass

    def test_create_model(self):
        """Test case for create_model

        Create Model  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_create_transcription(self):
        """Test case for create_transcription

        Create Transcription  # noqa: E501
        """
        pass

    def test_delete_base_model_log(self):
        """Test case for delete_base_model_log

        Delete Base Model Endpoint Log  # noqa: E501
        """
        pass

    def test_delete_base_model_logs(self):
        """Test case for delete_base_model_logs

        Delete All Base Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_delete_dataset(self):
        """Test case for delete_dataset

        Delete Dataset  # noqa: E501
        """
        pass

    def test_delete_endpoint(self):
        """Test case for delete_endpoint

        Delete Endpoint  # noqa: E501
        """
        pass

    def test_delete_endpoint_log(self):
        """Test case for delete_endpoint_log

        Delete Custom Model Endpoint Log  # noqa: E501
        """
        pass

    def test_delete_endpoint_logs(self):
        """Test case for delete_endpoint_logs

        Delete All Custom Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_delete_evaluation(self):
        """Test case for delete_evaluation

        Delete Evaluation  # noqa: E501
        """
        pass

    def test_delete_hook(self):
        """Test case for delete_hook

        Delete Web Hook  # noqa: E501
        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        Delete Model  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete Project  # noqa: E501
        """
        pass

    def test_delete_transcription(self):
        """Test case for delete_transcription

        Delete Transcription  # noqa: E501
        """
        pass

    def test_get_base_model(self):
        """Test case for get_base_model

        Get Base Model  # noqa: E501
        """
        pass

    def test_get_base_model_log(self):
        """Test case for get_base_model_log

        Get Base Model Endpoint Log  # noqa: E501
        """
        pass

    def test_get_base_model_logs(self):
        """Test case for get_base_model_logs

        Get Base Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_get_base_model_manifest(self):
        """Test case for get_base_model_manifest

        Get Base Model Manifest  # noqa: E501
        """
        pass

    def test_get_base_models(self):
        """Test case for get_base_models

        Get Base Models  # noqa: E501
        """
        pass

    def test_get_dataset(self):
        """Test case for get_dataset

        Get Dataset  # noqa: E501
        """
        pass

    def test_get_dataset_file(self):
        """Test case for get_dataset_file

        Get Dataset File  # noqa: E501
        """
        pass

    def test_get_dataset_files(self):
        """Test case for get_dataset_files

        Get Dataset Files  # noqa: E501
        """
        pass

    def test_get_datasets(self):
        """Test case for get_datasets

        Get Datasets  # noqa: E501
        """
        pass

    def test_get_datasets_for_project(self):
        """Test case for get_datasets_for_project

        Get Datasets for Project  # noqa: E501
        """
        pass

    def test_get_endpoint(self):
        """Test case for get_endpoint

        Get Endpoint  # noqa: E501
        """
        pass

    def test_get_endpoint_log(self):
        """Test case for get_endpoint_log

        Get Custom Model Endpoint Log  # noqa: E501
        """
        pass

    def test_get_endpoint_logs(self):
        """Test case for get_endpoint_logs

        Get Custom Model Endpoint Logs  # noqa: E501
        """
        pass

    def test_get_endpoints(self):
        """Test case for get_endpoints

        Get Endpoints  # noqa: E501
        """
        pass

    def test_get_endpoints_for_project(self):
        """Test case for get_endpoints_for_project

        Get Endpoints for Project  # noqa: E501
        """
        pass

    def test_get_evaluation(self):
        """Test case for get_evaluation

        Get Evaluation  # noqa: E501
        """
        pass

    def test_get_evaluation_file(self):
        """Test case for get_evaluation_file

        Get Evaluation File  # noqa: E501
        """
        pass

    def test_get_evaluation_files(self):
        """Test case for get_evaluation_files

        Get Evaluation Files  # noqa: E501
        """
        pass

    def test_get_evaluations(self):
        """Test case for get_evaluations

        Get Evaluations  # noqa: E501
        """
        pass

    def test_get_evaluations_for_project(self):
        """Test case for get_evaluations_for_project

        Get Evaluations for Project  # noqa: E501
        """
        pass

    def test_get_health_status(self):
        """Test case for get_health_status

        Get Health Status  # noqa: E501
        """
        pass

    def test_get_hook(self):
        """Test case for get_hook

        Get Web Hook  # noqa: E501
        """
        pass

    def test_get_hooks(self):
        """Test case for get_hooks

        Get Web Hooks  # noqa: E501
        """
        pass

    def test_get_model(self):
        """Test case for get_model

        Get Model  # noqa: E501
        """
        pass

    def test_get_model_manifest(self):
        """Test case for get_model_manifest

        Get Custom Model Manifest  # noqa: E501
        """
        pass

    def test_get_models(self):
        """Test case for get_models

        Get Custom Models  # noqa: E501
        """
        pass

    def test_get_models_for_project(self):
        """Test case for get_models_for_project

        Get Models for Project  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get Project  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Get Projects  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_datasets(self):
        """Test case for get_supported_locales_for_datasets

        Get Supported Locales for Datasets  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_endpoints(self):
        """Test case for get_supported_locales_for_endpoints

        Get Supported Locales for Endpoints  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_evaluations(self):
        """Test case for get_supported_locales_for_evaluations

        Get Supported Locales for Evaluations  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_models(self):
        """Test case for get_supported_locales_for_models

        Get Supported Locales for Models  # noqa: E501
        """
        pass

    def test_get_supported_locales_for_transcriptions(self):
        """Test case for get_supported_locales_for_transcriptions

        Get Supported Locales for Transcriptions  # noqa: E501
        """
        pass

    def test_get_supported_project_locales(self):
        """Test case for get_supported_project_locales

        Get Supported Locales for Projects  # noqa: E501
        """
        pass

    def test_get_transcription(self):
        """Test case for get_transcription

        Get Transcription  # noqa: E501
        """
        pass

    def test_get_transcription_file(self):
        """Test case for get_transcription_file

        Get Transcription File  # noqa: E501
        """
        pass

    def test_get_transcription_files(self):
        """Test case for get_transcription_files

        Get Transcription Files  # noqa: E501
        """
        pass

    def test_get_transcriptions(self):
        """Test case for get_transcriptions

        Get Transcriptions  # noqa: E501
        """
        pass

    def test_get_transcriptions_for_project(self):
        """Test case for get_transcriptions_for_project

        Get Transcriptions for Project  # noqa: E501
        """
        pass

    def test_ping_hook(self):
        """Test case for ping_hook

        Ping Web Hook  # noqa: E501
        """
        pass

    def test_test_hook(self):
        """Test case for test_hook

        Test Web Hook  # noqa: E501
        """
        pass

    def test_update_dataset(self):
        """Test case for update_dataset

        Update Dataset  # noqa: E501
        """
        pass

    def test_update_endpoint(self):
        """Test case for update_endpoint

        Update Endpoint  # noqa: E501
        """
        pass

    def test_update_evaluation(self):
        """Test case for update_evaluation

        Update Evaluation  # noqa: E501
        """
        pass

    def test_update_hook(self):
        """Test case for update_hook

        Update Web Hook  # noqa: E501
        """
        pass

    def test_update_model(self):
        """Test case for update_model

        Update Model  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass

    def test_update_transcription(self):
        """Test case for update_transcription

        Update Transcription  # noqa: E501
        """
        pass

    def test_upload_dataset_from_form(self):
        """Test case for upload_dataset_from_form

        Create Dataset from Form  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
